### ISSUE TITLE
调用链路问题

### ISSUE THREAD

**Issue by softliumin** [alipay/sofa-tracer#10]
我本地启动两个sofa项目A和B，http接口调用A项目之后调用rpc调用B项目，两个项目都开启上报数据到zipkin。但是在zipkin中查看调用链路，发现只有刚才的http接口链路，没有之后的rpc链路。zipkin中的traceId和spanId和sofa项目里面的traceId和spanId也不一样，请问是我没有配置好，还是项目还不支持rpc的调用链路？

**Comment by khotyn** [comment]
@softliumin  是支持的，你可以把你的项目 Push 到 Github 上，我们看下。

**Comment by softliumin** [comment]
@khotyn  https://github.com/softliumin/demo6 这是我的测试代码，谢谢了。

**Comment by khotyn** [comment]
@softliumin 看了一下你的代码，需要把工程依赖的 SOFABoot 的版本从 2.3.2 改成 2.4.0。因为 2.4.0 开始的 RPC 才对接了 Tracer：

```xml
<parent>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofaboot-dependencies</artifactId>
    <version>2.3.2</version>
</parent>
```

改成

```xml
<parent>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofaboot-dependencies</artifactId>
    <version>2.4.0</version>
</parent>
```

**Comment by softliumin** [comment]
@khotyn  rpc链路有数据了,Thanks
