### ISSUE TITLE
服务上报zipkin后的service-name是接口地址，不是application-name

### ISSUE THREAD

**Issue by dennis0721** [alipay/sofa-tracer#106]
如图：
![1540469693674](https://user-images.githubusercontent.com/23226155/47506984-d800cc80-d8a3-11e8-9f5f-a427e5706aac.jpg)
请问如何修改成服务名

**Comment by glmapper** [comment]
@dennis0721 是的，我们目前上报的service-name依赖的是span的operationName得到的。没有根据当前application-name来设定。

**Comment by dennis0721** [comment]
@glmapper 我觉得改用application-name会比较好

**Comment by dennis0721** [comment]
@glmapper 我觉得改用application-name会比较好
