### ISSUE TITLE
OpenTracingSpringMvcAutoConfiguration cannot disable

### ISSUE THREAD

**Issue by caojie09** [alipay/sofa-tracer#110]
### Describe the bug

The following code cannot disable OpenTracingSpringMvcAutoConfiguration: 

```java
@EnableAutoConfiguration(exclude={com.alipay.sofa.tracer.boot.springmvc.configuration.OpenTracingSpringMvcAutoConfiguration.class})
```

Because of `@ComponentScan` in SofaTracerAutoConfiguration

```java
@Configuration
@EnableConfigurationProperties(SofaTracerProperties.class)
@ComponentScan(value = { "com.alipay.sofa.tracer.boot" })
public class SofaTracerAutoConfiguration {
...
}
```

Spring Boot Document: [16.2 Disabling Specific Auto-configuration Classes](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html#using-boot-disabling-specific-auto-configuration)

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
has been fixed in 2.2.0
