### ISSUE TITLE
为什么不用opentacing 埋点？

### ISSUE THREAD

**Issue by wuyupengwoaini** [alipay/sofa-tracer#125]
既然sofa-tracer实现了opentracing协议，为什么不用opentracing的api来埋点呢？我看了下源代码，所有
埋点的插件都是用sofa-tracer的api埋点，我感觉这样就失去了实现opentracing协议的意义了。

opentracing有标准的埋点实现方式  https://github.com/opentracing-contrib，可以参考。

我的建议是，所有埋点都使用Opentracing的方式埋点

**Comment by QilongZhang** [comment]
@wuyupengwoaini  你说的是埋点方式是指什么？ Opentracing 只是定义了以个标准的接口规范，主要包括 `Tracer`, `Span`, `SpanContext`. 这些在 SOFATracer 都是兼容实现了的。

**Comment by wuyupengwoaini** [comment]
@khotyn  其实 [opentracing-contrib](https://github.com/opentracing-contrib) 开源项目中提供了很多的埋点组件了，如[java-spring-cloud](https://github.com/opentracing-contrib/java-spring-cloud) 就提供了Springcloud 环境下的所有埋点组件。只是这个埋点有的实现得不够好。我觉得埋点都是一样的，所以sofa-tracer的埋点可以直接采用opentracing-contrib中的埋点组件，只不过有些埋点需要优化。

sofa-tracer 的Contributor 也可以给opentracing-contrib提供好的埋点组件
