### ISSUE TITLE
service name error

### ISSUE THREAD

**Issue by limx198918** [alipay/sofa-tracer#13]
The Zipkin service name displays the URL address, which should be the application name

**Comment by guanchao-yang** [comment]
@limx198918 OpenTracing  Span converted to Zipkin Span and think that  ` Zipkin service name`  display application name which isn't graceful .In MVC , URL address more suitable for service name. And if show  application name can have more advantage？we can discuss it 😀

**Comment by limx198918** [comment]
If I have 10 projects and there are 20 services in each project, where do you show where 200 service addresses are, how can I quickly locate my service?

**Comment by guanchao-yang** [comment]
In the way，we can only use like this.

![image](https://user-images.githubusercontent.com/32863418/41579708-977160a0-73ca-11e8-86f9-d2846537f72a.png)

But we can better show in Zipkin like your suggestion. Can you contribute it 😀😀
