### ISSUE TITLE
相对鹰眼有什么特色，为什么要重新开发？

### ISSUE THREAD

**Issue by zhanglibinfast** [alipay/sofa-tracer#139]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
阿里的鹰眼是非常优秀的组件，不过阿里的鹰眼是比 SOFATracer 更大的一套东西，是一个非常完整的分布式链路追踪的解决方案，而 SOFATracer 是一个提供给用户方便集成 SOFAStack 下的其他的中间件以及其他的开源的组件的一个框架，在链路的采集，展示，分析上，SOFATracer 是直接对接了开源的 Zipkin 或者 Skywalking（未来）这样的组件，两者的定位不完全一样。

当然 SOFATracer 在 TraceId 以及 SpanId 的生成等地方是参考了鹰眼的机制。
