### ISSUE TITLE
support manual reporting data

### ISSUE THREAD

**Issue by limx198918** [alipay/sofa-tracer#14]
Provide Zipkin service reporting method, support manual reporting data, more flexible

**Comment by guanchao-yang** [comment]
@limx198918 SOFATracer based on OpenTracing API, so we can use SOFATracer API and convert Model to Zipkin through SOFATracer API we have flexible function.

**Comment by limx198918** [comment]
Where can SOFATracer API be seen?

**Comment by guanchao-yang** [comment]
@limx198918 [Here](https://github.com/alipay/sofa-tracer/wiki/Utils)

**Comment by limx198918** [comment]
sofatracecontext sofatracecontext = sofatracecontextholder .getsofatracecontext（）；
sofatracecontext能支持上报吗，里面的push方法是的吗吗？

**Comment by guanchao-yang** [comment]
@limx198918 里面操作的对象是 SOFATracer Span 基于 OpenTracing 的 Span 标准，可以向 Span 中按照 OpenTracing 的方式存放 Tags 或者 Baggage，到时候模型转化的时候，会转为 Zipkin 的 模型。
