### ISSUE TITLE
非http请求线程的TraceId和SpaceId

### ISSUE THREAD

**Issue by guzhangyu** [alipay/sofa-tracer#15]
如果不是http产生的请求，而是自己产生的线程，有生成相应的TraceId 和 SpaceId的方法吗？
我这边手动往MDC里塞值，在rpc调用的时候会被冲掉;有什么不被冲掉的方法吗？

**Comment by guanchao-yang** [comment]
> 如果不是http产生的请求，而是自己产生的线程，有生成相应的TraceId 和 SpaceId的方法吗？

这个问题就相当于你是作为请求的第一个发起方，可以直接通过 OpenTracing 的方式构建一个 Span，可以类似这样去构建：

```
//开始，当然  this.sofaTracer 是需要继承构建好的实例，简单的可以看下 `com.alipay.sofa.tracer.plugins.springmvc.SpringMvcTracer` 构建方法
SofaTracerSpan span = (SofaTracerSpan) this.sofaTracer.buildSpan("testInjectSpan")
            .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_CLIENT).start();
//结束
span.finish();
```

> 我这边手动往MDC里塞值，在rpc调用的时候会被冲掉;有什么不被冲掉的方法吗？ 

如果 MDC 对应打印的字段是[这个文档描述的方式](https://github.com/alipay/sofa-tracer/wiki/PrintTraceIdSpanId)，那么在同一个线程中发生 RPC 调用时，在结束前都会是 RPC 根据你的当前 Span 构造的 Child Span，那么复写就是正常的。如果在 RPC 调用结束后或者开始 RPC 调用前自己向  MDC 中塞值是可以生效的。如果是作为服务引用方，那么可以在被引用的服务发生调用时，在方法前后进行复写 MDC ，但是我们一般不建议大家去覆盖默认的值，如果变为比较随意的值是不易于链路的“串联”的。

**Comment by guzhangyu** [comment]
对于需要自己生成TraceId和SpaceId的实践：
1、起始处增加如下代码：
```
SofaTraceContext sofaTraceContext=SofaTraceContextHolder.getSofaTraceContext();
        SofaTracerSpan span = sofaTraceContext.getCurrentSpan();
        if(span==null){//防止覆盖
            span= (SofaTracerSpan) SpringMvcTracer.getSpringMvcTracerSingleton().getSofaTracer().buildSpan("testInjectSpan")
                    .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_CLIENT).start();
            sofaTraceContext.push(span);
        }
```

2、结束处：
```
 span.finish();
 sofaTraceContext.pop();
```

**Comment by khotyn** [comment]
异步处理还有一种更加简单的方式，用我们提供的工具类包装一下 Runnable 或者 Callable 就可以了。https://github.com/alipay/sofa-tracer/wiki/Async#%E5%BC%82%E6%AD%A5%E7%BA%BF%E7%A8%8B%E5%A4%84%E7%90%86

**Comment by billowqiu** [comment]
[ttl](https://github.com/alibaba/transmittable-thread-local)，思路是一样的
