### ISSUE TITLE
建议传统spring项目支持加强

### ISSUE THREAD

**Issue by vwyuheng** [alipay/sofa-tracer#153]
### Your question

传统spring项目发现一些配置生效问题，比如输出日志是json格式等，希望加强通用和统一

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version: 2.3.0
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):mac osx
- Maven version: 3.x
- IDE version:idea

**Comment by khotyn** [comment]
现在 SOFATracer 默认输出是 JSON 格式的，你是想调整成什么样的格式的？

**Comment by vwyuheng** [comment]
@khotyn 我的意思是tracer-self 日志和static的日志还不是json格式，另外各个plugin组件的日志输出格式有的实现有自己的开关配置，是否输出成json格式，这些开关是不是要统一起来比较好

**Comment by glmapper** [comment]
@vwyuheng 你指的是哪个插件？SOFATracer目前的日志格式就是json，具体的输出内容会根据不同的插件扩展需要收集的信息有所区别；开关这块没有提供关于格式的控制的
