### ISSUE TITLE
请教数据源埋点问题

### ISSUE THREAD

**Issue by wuyupengwoaini** [alipay/sofa-tracer#154]
之前看opentracing的埋点机制基本上基于AOP以及BeanPostProcessor，今天有幸看到了Sofa-tracer的DataSource埋点方式是基于BeanFactoryPostProcessor，我想请问一下Sofa-tracer的这种埋点方式有什么特别考虑的地方，因为我觉得基于BeanFactoryPostProcessor的埋点在Spring API级别上是稍微复杂一点，所以代价有点大，可否能告知Sofa-tracer基于BeanFactoryPostProcessor的埋点是有什么特别的初衷吗

**Comment by QilongZhang** [comment]
两种方案实现起来都差不多，也不负责，只是 BeanFactoryPostProcessor 相对使用较少。相对于 BeanPostProcessor，目前的方案拿配置的属性会更简单点。

**Comment by wuyupengwoaini** [comment]
配置的属性具体是指什么呢

**Comment by QilongZhang** [comment]
> 配置的属性具体是指什么呢

目前支持的 tomcat/dbcp/druid/c3p0/hikari 只有 jdbc url 这一个属性。

**Comment by wuyupengwoaini** [comment]
好的，我明白了。期盼sofa-tracer能够写一篇博文介绍一下具体的埋点技术，学习一下

**Comment by glmapper** [comment]
@wuyupengwoaini 可以关注下 [SOFATracer 剖析系列](https://www.yuque.com/huarou/gd4szw/tr3qab#ug3tle)。

插件分析篇的安排：
![image](https://user-images.githubusercontent.com/35319286/51100551-954ef080-1811-11e9-8657-b171ee8cedb8.png)
