### ISSUE TITLE
Mac idea package 出错

### ISSUE THREAD

**Issue by krisjin** [alipay/sofa-tracer#168]
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ sofa-tracer-okhttp-plugin ---
[INFO] Building jar: /usr/local/git-code/sofa-tracer/sofa-tracer-plugins/sofa-tracer-okhttp-plugin/target/sofa-tracer-okhttp-plugin-2.3.1-sources.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ sofa-tracer-okhttp-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tracer-all-parent .................................. SUCCESS [  2.040 s]
[INFO] tracer-core ........................................ SKIPPED
[INFO] tracer-extensions .................................. SKIPPED
[INFO] sofa-tracer-springmvc-plugin ....................... SKIPPED
[INFO] sofa-tracer-httpclient-plugin ...................... SKIPPED
[INFO] sofa-tracer-okhttp-plugin .......................... FAILURE [  3.593 s]
[INFO] sofa-tracer-datasource-plugin ...................... SKIPPED
[INFO] sofa-tracer-resttmplate-plugin ..................... SKIPPED
[INFO] sofa-tracer-zipkin-plugin .......................... SKIPPED
[INFO] SOFATracer in one without SOFABoot starter ......... SKIPPED
[INFO] tracer-sofa-boot-starter ........................... SKIPPED
[INFO] sofa-tracer-samples ................................ SUCCESS [  0.168 s]
[INFO] sofa-tracer-sample-with-springmvc .................. SKIPPED
[INFO] sofa-tracer-sample-with-zipkin ..................... SKIPPED
[INFO] sofa-tracer-sample-with-slf4j ...................... SKIPPED
[INFO] sofa-tracer-sample-with-sofarpc .................... SKIPPED
[INFO] tracer-sample-with-httpclient ...................... SKIPPED
[INFO] sofa-tracer-sample-with-h2 ......................... SKIPPED
[INFO] tracer-sample-with-resttemplate .................... SKIPPED
[INFO] tracer-sample-with-sampler ......................... SUCCESS [  0.712 s]
[INFO] sofa-tracer-core-test .............................. SKIPPED
[INFO] sofa-tracer-logback-test ........................... SKIPPED
[INFO] sofa-tracer-log4j2-test ............................ SKIPPED
[INFO] sofa-tracer-log4j-test ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.030 s (Wall Clock)
[INFO] Finished at: 2019-02-12T23:21:35+08:00
[INFO] Final Memory: 90M/1234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project sofa-tracer-okhttp-plugin: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sofa-tracer-okhttp-plugin

Process finished with exit code 1

**Comment by glmapper** [comment]
@krisjin "Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]".please check your environment variable .

**Comment by krisjin** [comment]
thanks ,it's resolved。
