### ISSUE TITLE
SOFATracer support HttpClient plugin

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-tracer#17]
SOFATracer support HttpClient plugin ,when we use Apache httpclient such as 

```xml
dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.2</version>
</dependency>
```
We can print SOFATracer httpclient log and also can report to Zipkin. We suggest that httpclient version more than `4.5.0`.

**Comment by HuangSheng** [comment]
@guanchao-yang 问一下，你们httpClientd的支持是用4.5.0+的版本吗？有计划兼容旧一点的4.3.0+版本么？包括3.X版本的httpClient。
还有这些都是用的plugin的方式支持吗？

**Comment by guanchao-yang** [comment]
@HuangSheng 这些都是以 Plugin 的方式提供。首先支持的是 4.5.0 的最新版本，然后之前的 4.X 版本也会考虑支持。像 3.X 的版本，可能优先级不那么高了哈，这里期望大家一起贡献下哈。

**Comment by guanchao-yang** [comment]
And also support http aync client plugin for SOFA Tracer .And support httpasyncclient version is 4.1.X.

```
<dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpasyncclient</artifactId>
                <version>4.1.X</version>
            </dependency>
```
