### ISSUE TITLE
其他语言怎么接入？

### ISSUE THREAD

**Issue by onlyshow** [alipay/sofa-tracer#194]

**Comment by glmapper** [comment]
@onlyshow 目前 SOFATracer 版本仅支持 JAVA 语言环境下使用

**Comment by onlyshow** [comment]
> 同时，这些应用又构建在不同的软件模块上，这些软件模块，有可能是由不同的团队开发，可能使用不同的编程语言来实现、有可能部署了几千台服务器。因此，就需要一些可以帮助理解各个应用的线上调用行为，并可以分析远程调用性能的组件。
有计划支持吗？

**Comment by glmapper** [comment]
> 「有可能是由不同的团队开发，可能使用不同的编程语言来实现」
@onlyshow SOFATracer 是基于java 版本的 OpenTracing API 实现的，本身就是 OpenTracing 规范的一种实现方式。

> 「有计划支持吗？」
目前 SOFATracer 多语言支持这块还没有具体计划，不过这也是 SOFATracer 需要完善的重要能力，欢迎给我们 PR 这方面的功能。
