### ISSUE TITLE
Tracer dependency management

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-tracer#20]
Tracer module dependency better, `tracer-sofa-boot-starter` can run in SOFABoot and Spring Boot。And also we can provide `sofatracer-all` depend on other tracer modules.Other components can only depend on `sofatracer-all`.

**Comment by HuangSheng** [comment]
@guanchao-yang 现在的zipkin集成是在tracer-sofa-boot-starter项目中的，我们现在的项目没有使用spring boot，如果想集成的话会很麻烦。建议用plugin的方式做成单独的组件，starter只是简化配置，保证不用boot的项目也可以正常使用
