### ISSUE TITLE
什么时候能支持dubbo

### ISSUE THREAD

**Issue by 285976754** [alipay/sofa-tracer#203]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
已经PR https://github.com/alipay/sofa-tracer/pull/183

**Comment by 285976754** [comment]
> 已经PR #183

如何集成，有手册吗？

**Comment by glmapper** [comment]
> > 已经PR #183
> 
> 如何集成，有手册吗？

本周将会发布 SOFATracer 2.4.0/3.0.4 版本，集成手册会同步出来，请关注~

**Comment by 285976754** [comment]
> > > 已经PR #183
> > 
> > 
> > 如何集成，有手册吗？
> 
> 本周将会发布 SOFATracer 2.4.0/3.0.4 版本，集成手册会同步出来，请关注~

好的，期待ing!!!
