### ISSUE TITLE
如何关闭SOFATracer的功能

### ISSUE THREAD

**Issue by opjkjava** [alipay/sofa-tracer#209]
### Your question
文档中描述 
“在SOFARPC(5.4.0及之后的版本) 后的版本中，我们集成了SOFATracer的功能，默认开启，可以输出链路中的数据信息。”

如何配置关闭改功能。

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)
我们的分布式系统简单，有时候部署到同一个机器上。希望关闭SOFATracer的功能，提高调用效率。

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
可以看下这个文档哦：https://www.sofastack.tech/sofa-rpc/docs/Tracing-Usage

另外，请问你们是在生产上使用吗？方便在这里登记吗？https://github.com/alipay/sofastack-doc/issues/42

**Comment by khotyn** [comment]
如果没有其他问题，这个 ISSUE 先关闭掉了，还有问题可以再开 ISSUE 哦。
