### ISSUE TITLE
SOFATracer Support Zipkin version 2.X.X 

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-tracer#23]
### Describe 

SOFATracer report to Zipkin version is `1.19.2` by default

### Expected behavior

SOFATracer report Zipkin client support 2.X.X version

### Actual behavior
 
Only verify Zipkin  version `1.19.X`

**Comment by HuangSheng** [comment]
测试使用zipkin2.9.4版本是OK的，没有兼容性问题，服务端和客户端都使用2.9.4版本，但是zipkin-reporter只能使用1.1.2版本，不能使用2.X.X版本的，那个版本看了下，包名改了，需要做兼容。
**附客户端依赖**：
```
                <dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin</artifactId>
			<version>2.9.4</version>
		</dependency>
		<dependency>
			<groupId>io.zipkin.reporter</groupId>
			<artifactId>zipkin-reporter</artifactId>
			<version>1.1.2</version>
		</dependency>

**Comment by guanchao-yang** [comment]
@HuangSheng 可以直接 PR 上来哈，我们兼容掉高低版本的  `zipkin-reporter`
