### ISSUE TITLE
Provide a sampling functionality to tracer

### ISSUE THREAD

**Issue by khotyn** [alipay/sofa-tracer#31]
Sometimes, report/print every tracing will consume a lot of resource, SOFATracer can add a sampling functionality so that SOFATracer don't have to report/print every tracing.

**Comment by guanchao-yang** [comment]
@glmapper We have provided the [algorithm code](https://github.com/alipay/sofa-tracer/blob/ba91fb08a8be0d9185b9dd3df5852b44149460b9/tracer-core/src/main/java/com/alipay/common/tracer/core/samplers/SofaTracerPercentageBasedSampler.java) and [SofaTracer sample strategy code](https://github.com/alipay/sofa-tracer/blob/ba91fb08a8be0d9185b9dd3df5852b44149460b9/tracer-core/src/main/java/com/alipay/common/tracer/core/SofaTracer.java#L299) .We verify or fix it and write the user document.
