### ISSUE TITLE
建议不用spring boot也可以使用sofa-tracer并且上报zipkin

### ISSUE THREAD

**Issue by HuangSheng** [alipay/sofa-tracer#32]
现在的zipkin集成是在tracer-sofa-boot-starter项目中的，我们现在的项目没有使用spring boot，如果想集成的话会很麻烦。建议用plugin的方式做成单独的组件，starter只是简化配置，保证不用boot的项目也可以正常使用

**Comment by guanchao-yang** [comment]
[源自](https://github.com/alipay/sofa-tracer/issues/20)

**Comment by billowqiu** [comment]
同求

**Comment by guanchao-yang** [comment]
@billowqiu  2.2.0 我们迭代 RELEASE 这个能力。也非常非常欢迎给我们 PR 哈。

**Comment by billowqiu** [comment]
已经发布了，有对应的sampler么？

**Comment by glmapper** [comment]
@billowqiu 有的，参考[这里](https://github.com/glmapper/tracer-zipkin-plugin-demo)

**Comment by uugit** [comment]
请问非springboot项目, 如何使用zipkin上报

**Comment by glmapper** [comment]
> 请问非springboot项目, 如何使用zipkin上报

参考上一个 comment
