### ISSUE TITLE
如何将生成的追踪信息不打印到日志中，而在代码中获取？我需要做持久化

### ISSUE THREAD

**Issue by zjcnb** [alipay/sofa-tracer#33]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by guanchao-yang** [comment]
> 如何将生成的追踪信息不打印到日志中

配置 `com.alipay.sofa.tracer.disableDigestLog=true` 将不会打印日志到文件中。[配置文档](https://github.com/alipay/sofa-tracer/wiki/Configuration)

> 而在代码中获取？我需要做持久化
通过上下文中获取 Span 如 `SofaTracerSpan sofaTracerSpan = sofaTraceContext.getCurrentSpan();` 获取的 Span 就是链路调用信息的抽象。[参考工具类](https://github.com/alipay/sofa-tracer/wiki/Utils)

**Comment by zjcnb** [comment]
thanks ,but  I have yet a question！

请问这个是服务追踪的一些信息，但是没有状态码什么的
[{
	"fields":{
		"event":"sr"
	},
	"time":1531714665907
}]
{"span.kind":"server","current.thread.name":"http-nio-8080-exec-1","request.url":"http://127.0.0.1:8080/getUserById","method":"GET"}
{}
{"req.size.bytes":-1}
{
	"bizBaggage":{},
	"bizSerializedBaggage":"",
	"childContextIndex":0,
	"parentId":"",
	"sampled":false,
	"spanId":"0",
	"sysBaggage":{},
	"sysSerializedBaggage":"",
	"traceId":"ac1e0016153171466590410011834"
}


其他的如果我需要，是不是根据OpenTracing规范去取呢？

**Comment by zjcnb** [comment]
不单单是状态码，我给你看一下日志输出的吧，都有这些信息：
{"time":"2018-07-16 11:46:13.260","local.app":"null","traceId":"ac1e0016153171276940610011786","spanId":"0","request.url":"http://127.0.0.1:8080/getUserById","method":"GET","result.code":"200","req.size.bytes":-1,"resp.size.bytes":84,"time.cost.milliseconds":3853,"current.thread.name":"http-nio-8080-exec-1","baggage":""}

而我代码里面获得的呢，是这些信息：
{
	"bizBaggage":{},
	"bizSerializedBaggage":"",
	"childContextIndex":0,
	"parentId":"",
	"sampled":false,
	"spanId":"0",
	"sysBaggage":{},
	"sysSerializedBaggage":"",
	"traceId":"ac1e0016153171789576510011911"
}

**Comment by guanchao-yang** [comment]
@zjcnb 你的这个示例是用 Spring MVC 的，可以在 请求的时候，使用  `SofaTracerSpan sofaTracerSpan = sofaTraceContext.getCurrentSpan();` 获取 Span，然后通过 `com.alipay.common.tracer.core.span.SofaTracerSpan#getTagsWithStr("${tagKey}")`，但是 result.code 是获取不到的，因为 result.code 是在你的 Controller 被**调用完成后**才设置的这个值，而你获取的时候，应该是**调用中**，具体可以调试[看下这里代码](https://github.com/alipay/sofa-tracer/blob/master/sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcSofaTracerFilter.java#L78)

**Comment by zjcnb** [comment]
我可以写一个拦截器，A服务调用B服务，A服务方法请求执行完之后再走
public void postHandle(HttpServletRequest request,
	                       HttpServletResponse response,
	                       Object handler,
	                       ModelAndView modelAndView) throws Exception {
		//获取请求的上下文
		SofaTraceContext sofaTraceContext = SofaTraceContextHolder.getSofaTraceContext();
		//从ThreadLocal中获取调用服务的信息
		SofaTracerSpan sofaTracerSpan = sofaTraceContext.getCurrentSpan();
		Map<String,String> map = sofaTracerSpan.getTagsWithStr();
		String result = map.get("${tagKey}");


	}

还有想要确定一下的是，这个获取traceId这些信息，是请求之前获取好，还是请求结束之后获取好呢

**Comment by guanchao-yang** [comment]
> 还有想要确定一下的是，这个获取traceId这些信息，是请求之前获取好，还是请求结束之后获取好呢

这里就涉及到 traceId 的生成地方，traceId 是在每一个请求的 Filter 中产生的。不存在之前/后 好坏的问题哈。只要在请求的 SpringMvcSofaTracerFilter 生成了  traceId 后你都可以获取到。
@zjcnb

**Comment by zjcnb** [comment]
嗯嗯，好

**Comment by guanchao-yang** [comment]
@zjcnb 第二个问题，你想咨询的是为什么 traceId 不同的问题，是吧？

因为你的这两个服务分别是服务 A 和服务 B，而这两个分别响应  MVC 的请求，而请求的上下文中没有能够还原出 SpanContext 的数据，所以这两个请求就会认为这次请求是链路的开始，就会重新生成一个 traceId 同时  spanId 均是 0 ，关于 [traceId 和 spanId 可以参考文档](https://github.com/alipay/sofa-tracer/wiki/TraceIdGeneratedRule)。而如果请求上下文中携带了 SpanContext 的信息即可以还原出 Span，并构造 ChildSpan，这个功能目前正在 Review 中，[可以参考这里多提意见](https://github.com/alipay/sofa-tracer/pull/30)。

**Comment by zjcnb** [comment]
嗯，知道了。其实目前开源的现有功能，是不支持服务A和服务B之间传递traceid的吧

**Comment by guanchao-yang** [comment]
@zjcnb [RPC 组件是支持的](https://github.com/alipay/sofa-rpc)。另，如上文，相应的组件我们逐步 
 [Roadmap 支持上](https://github.com/alipay/sofa-tracer/wiki/RoadMap)，到时候 HttpClient 和 SpringMVC 也是可以的。

**Comment by khotyn** [comment]
@zjcnb 服务 A 调用服务 B 你们用的是什么？

**Comment by zjcnb** [comment]
用的springclould

**Comment by zjcnb** [comment]
@guanchao-yang 好的

**Comment by khotyn** [comment]
@zjcnb 具体用的 SpringCloud 里面的哪个组件，HttpClient？RestTemplate 还是啥？能够贴一下关键的代码信息么？

**Comment by zjcnb** [comment]
用的@RestController。mvc模式吧

**Comment by khotyn** [comment]
@zjcnb RestController 是提供服务吧？调用是怎么调用的？
