### ISSUE TITLE
关于日志的疑问

### ISSUE THREAD

**Issue by arebya** [alipay/sofa-tracer#38]
1、“提供异步落地磁盘的日志打印能力”
——————-这个使用log4j2的AsyncLogger就可以搞定吧？为什么通过集成disruptor的源代码而不是依赖jar包的方式呢？

2、另外看到工程里的slf4j-api和slf4j-log4j有多个版本，感觉较乱。
![image](https://user-images.githubusercontent.com/1525048/43297963-8a97ab26-9186-11e8-9bd5-25e3ac866e85.png)

**Comment by guanchao-yang** [comment]
@arebya 

> 这个使用log4j2的AsyncLogger就可以搞定吧？为什么通过集成disruptor的源代码而不是依赖jar包的方式呢？

Log4j2 也是使用 disruptor 做的打印，你说的没错可以做到这样。集成的主要目的就是为了 SOFATracer 能够自包含，不对外部依赖或者容易产生冲突的依赖做版本协商。

> 另外看到工程里的slf4j-api和slf4j-log4j有多个版本，感觉较乱。

因为工程中有针对 log4j 和 log4j2 的用例，均在这个 `tracer-test` 测试模块中，所以会对日志实现和桥接包做了依赖，主要是做验证。里面出现了通个 GV 的多个版本，[我们在 2.1.2 迭代中马上优化掉](https://github.com/alipay/sofa-tracer/issues/39)。
