### ISSUE TITLE
ZipkinSofaTracerAutoConfiguration.class自动配置无效

### ISSUE THREAD

**Issue by zzps** [alipay/sofa-tracer#70]
### Describe the bug
按照gitub上报Zipkin文档操作
tracer-sofa-boot-starter源码中的ZipkinSofaTracerAutoConfiguration自动配置类中
配置此自动配置生效的条件@ConditionalOnClass中的（zipkin.Span.class, zipkin.reporter.AsyncReporter.class）是找不到的，在文档中也没有提示这是什么类，
导致自动配置不生效，经过检查发现是GitHub上文档提示的引入jar包依赖不对，
找不到的类文件在<dependency>
                                <groupId>io.zipkin.java</groupId>
                                <artifactId>zipkin</artifactId>
                                <version>1.19.2</version>
                             </dependency>
中找到。希望能够在源码和文档上进行改正，谢谢
ZipkinSofaTracerAutoConfiguration自动配置不生效
### Expected behavior
希望改造GitHub文档和源码
### Minimal yet complete reproducer code (or GitHub URL to code)
@ConditionalOnClass({ zipkin.Span.class, zipkin.reporter.AsyncReporter.class })
public class ZipkinSofaTracerAutoConfiguration {
-------------------------------------------------省略
}
### Environment

- SOFATracer version:2.1.4
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@zzps 抱歉，2.1.4 版本中主要是修复了异步servlet的问题。目前文档中[使用 SOFATracer 远程汇报数据到 Zipkin](https://github.com/alipay/sofa-tracer/tree/master/tracer-samples/tracer-sample-with-zipkin) 使用的版本是zipkin v2 模型进行上报的，[#23](https://github.com/alipay/sofa-tracer/issues/23) 、[#65](https://github.com/alipay/sofa-tracer/issues/65)。后续版本中将不在支持zipkin v1模型的上报能力，这部分的主要原因是考虑到zipkin v2在于模型上一些优化。

关于你的提到的“希望改造GitHub文档和源码”，我们会在2.2.0 版本中完善。

感谢你的建议。
