### ISSUE TITLE
netty+resteasy rest接口未打印trace日志

### ISSUE THREAD

**Issue by rayzeng** [alipay/sofa-tracer#73]
### Your question

sofarpc启动netty+resteasy的rest接口，并没有记录trace日志
bolt接口和spring mvc格式的有记录

### Your scenes
server.port=8080
com.alipay.sofa.rpc.restPort=18080
com.alipay.sofa.rpc.restContextPath=/demo
com.alipay.sofa.rpc.boltPort=28080
按这个配置，调用8080和28080的接口都有trace日志，分别在rpc-client-digest.log和spring-mvc-digest.log中，但未找到18080的日志，接口可以正常响应

### Environment

- SOFATracer version:2.1.4
- JVM version (e.g. `java -version`):1.8

**Comment by QilongZhang** [comment]
@rayzeng  你好，能否提供相应的demo?  SOFATracer 是支持 rest 日志接口打印的，也是在 rpc-client-digest.log 和 rpc-server-digest.log 日志中的。

**Comment by rayzeng** [comment]
[sofaboot-sample-with-rpc.zip](https://github.com/alipay/sofa-tracer/files/2399355/sofaboot-sample-with-rpc.zip)
测试了下，如果在pom中增加starter就不能记录，不增加反而可以
<dependency>
        <groupId>com.alipay.sofa</groupId>
        <artifactId>tracer-sofa-boot-starter</artifactId>
 </dependency>

**Comment by QilongZhang** [comment]
@rayzeng  麻烦把你的客户端也发下， 另外能否贴下错误堆栈？ 我这边在服务端测试按你说的添加了 tracer-sofa-boot-starter，没有出现报错，正常打印日志。

**Comment by rayzeng** [comment]
客户端是http请求，直接在浏览器发起
http://127.0.0.1:8081/demo/test/time/123

**Comment by QilongZhang** [comment]
@rayzeng  我这边是正常打印日志不报错，另外你没有配置zipkin也不会上报。

**Comment by QilongZhang** [comment]
@rayzeng  如果没有其他问题，我关掉这个issue.
