### ISSUE TITLE
can support httpclient4.2 version

### ISSUE THREAD

**Issue by limx198918** [alipay/sofa-tracer#78]
Whether you can support httpclient4.2 version, old projects may not be developed according to the version supported by sofa tracer.

**Comment by guanchao-yang** [comment]
@limx198918 OK, we will verify.

**Comment by guanchao-yang** [comment]
@limx198918  Now, verification result

```xml
 <!-- HttpClient Dependency -->
 <dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>${apache.httpclient.version}</version>
</dependency>
```

Now , HttpClient  ${apache.httpclient.version} support version is between `4.3.X` and  `4.5.X` latest. And we will support `org.apache.httpcomponents:httpclient:4.2.X` vesion next iteration.  @limx198918 Please pay attention.

**Comment by glmapper** [comment]
Major changes have been made in the httpclient 4.3.x version, and such as DefaultHttpClient in httpclient 4.2.x is marked as Deprecated. So considering the compatibility issues of httclient itself, SOFATracer will only support httpclient v4.3+
